name: publish

on:
  push:
    branches: ["main"]
    paths-ignore:
      - 'README.md'
      - '.gitignore'
      - '.editorconfig'
      - 'example'
    
env:
  dotnet: 7.0.x
    
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 10
          
      - name: Configure .NET SDK ${{ env.dotnet }}
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: ${{ env.dotnet }}
          
      - name: Generating version
        id: versioning
        uses: mathieudutour/github-tag-action@v6.1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          default_bump: patch
          release_branches: main
          tag_prefix: ''
          dry_run: true    
          
      - name: .NET Restore
        run: dotnet restore
      
      - name: .NET Build
        run: dotnet build --no-restore -c Release /p:Version=${{ steps.versioning.outputs.new_tag }}
        
      - name: .NET Pack
        run: dotnet pack -c Release --no-build /p:Version=${{ steps.versioning.outputs.new_tag }}
        
      - name: .NET Nuget
        run: dotnet nuget push **/*.nupkg \
          --source https://nuget.pkg.github.com/roxeez/index.json \
          --api-key ${{ secrets.NUGET_TOKEN }} \
          --skip-duplicate
        
      - name: Create tag
        uses: mathieudutour/github-tag-action@v6.1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          tag_prefix: ''
          custom_tag: ${{ steps.versioning.outputs.new_tag }}